sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install -U pip
  - pip install pytest-xdist
  - pip install tensorflow
  - pip install .
script: pytest -s
notifications:
  email:
    recipients:
      - contact@reinforce.io
    on_success: never
    on_failure: always